# Generated by Django 5.2.1 on 2025-05-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
