# Generated by Django 5.2.1 on 2025-05-21 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_codigo_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
