# Generated by Django 5.2.1 on 2025-05-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_remove_produto_imagem_produto_imagem_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Imagem_2',
            field=models.ImageField(blank=True, default='images_produts/default.jpg', upload_to='images_produts', verbose_name='Imagem 2 do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='Imagem_3',
            field=models.ImageField(blank=True, default='images_produts/default.jpg', upload_to='images_produts', verbose_name='Imagem 3 do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='Imagem_4',
            field=models.ImageField(blank=True, default='images_produts/default.jpg', upload_to='images_produts', verbose_name='Imagem 4 do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='Imagem_5',
            field=models.ImageField(blank=True, default='images_produts/default.jpg', upload_to='images_produts', verbose_name='Imagem 5 do Produto'),
        ),
        migrations.DeleteModel(
            name='ImagensExtrasProduto',
        ),
    ]
