# Generated by Django 5.2.1 on 2025-05-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produto_imagem_2_produto_imagem_3_produto_imagem_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Imagem_5',
        ),
    ]
