# Generated by Django 5.2.1 on 2025-07-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
